name: roboaware
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - colorlog=4.4.0=py37hc8dfbb8_1
  - cudatoolkit=11.0.221=h6bb024c_0
  - cytoolz=0.11.0=py37h7b6447c_0
  - dask-core=2.30.0=py_0
  - decorator=4.4.2=py_0
  - freetype=2.10.4=h5ab3b9f_0
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - imageio=2.9.0=py_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.2=heb0550a_3
  - matplotlib-base=3.3.2=py37h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - ninja=1.10.1=py37hfd86e86_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h516909a_0
  - pip=20.2.4=py37h06a4308_0
  - pyparsing=2.4.7=py_0
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.7.0=py3.7_cuda11.0.221_cudnn8.0.3_0
  - pywavelets=1.1.1=py37h7b6447c_2
  - quaternion=2020.9.5.14.42.2=py37h161383b_1
  - readline=8.0=h7b6447c_0
  - scikit-image=0.17.2=py37hdf5156a_0
  - scipy=1.5.2=py37h0b6359f_0
  - setuptools=50.3.1=py37h06a4308_1
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tifffile=2020.10.1=py37hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=py_0
  - torchvision=0.8.1=py37_cu110
  - tornado=6.0.4=py37h7b6447c_1
  - typing_extensions=3.7.4.3=py_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - appnope==0.1.0
    - backcall==0.2.0
    - cffi==1.14.2
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.3.0
    - configparser==5.0.1
    - cycler==0.10.0
    - cython==0.29.21
    - docker-pycreds==0.4.0
    - fasteners==0.15
    - flake8==3.8.3
    - future==0.18.2
    - gitdb==4.0.5
    - gitpython==3.1.11
    - glfw==1.12.0
    - gym==0.17.2
    - idna==2.10
    - importlib-metadata==2.0.0
    - ipdb==0.13.3
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - kiwisolver==1.2.0
    - matplotlib==3.3.1
    - mccabe==0.6.1
    - monotonic==1.5
    - mujoco-py==2.0.2.13
    - numpy==1.19.1
    - parso==0.7.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - promise==2.3
    - prompt-toolkit==3.0.7
    - protobuf==3.13.0
    - psutil==5.7.3
    - ptyprocess==0.6.0
    - pycodestyle==2.6.0
    - pycparser==2.20
    - pyflakes==2.2.0
    - pyglet==1.5.0
    - pygments==2.6.1
    - pyquaternion==0.9.9
    - pyyaml==5.3.1
    - requests==2.24.0
    - sentry-sdk==0.19.2
    - shortuuid==1.0.1
    - smmap==3.0.4
    - subprocess32==3.5.4
    - torch==1.6.0
    - tqdm==4.48.2
    - traitlets==4.3.3
    - urllib3==1.26.0
    - wandb==0.10.10
    - watchdog==0.10.3
    - wcwidth==0.2.5
    - zipp==3.4.0
